In [34]:
path = './data/val2017.txt'
with open(path, 'r') as f:
    datas = f.readlines()
    
for i in range(len(datas)):
    datas[i] = 'data/val2017/' + datas[i]

In [35]:
path = './data/val2017-v2.txt'
with open(path, 'w') as f:
    for s in datas:
        f.write(s)

In [5]:
path = './data/val2017-v2.txt'
with open(path, 'r') as f:
    datas = f.readlines()
    
path = './data/val2017-image.txt'
with open(path, 'w') as f:
    for s in datas:
        c = s.split(' ')[0] + '\n'
        f.write(c)

# image、label

In [1]:
import json

# bbox : x, y, w, h
with open('./data/annotations/instances_val2017.json', 'r') as f:
    d = json.load(f)
labels = d['annotations']

In [2]:
from tqdm import tqdm
import os
import cv2

images_path = os.listdir('./data/val2017/')
for label in tqdm(labels):
    image_id = str(label['image_id'])
    
    p = '0' * (12 - len(image_id)) + image_id
    label_p = p + '.txt'
    img_p = os.path.join('./data/val2017/', p + '.jpg')
    h, w, _ = cv2.imread(img_p).shape
    
    category_id = str(label['category_id'])
    
    i1, i2, i3, i4 = label['bbox'][0], label['bbox'][1], label['bbox'][2], label['bbox'][3]
    
#     i1, i2, i3, i4 = label['bbox'][0] / w, label['bbox'][1] / h, label['bbox'][2] / w, label['bbox'][3] / h
#     i1, i2 = i1 - i3 / 2, i2 - i4 / 2
#     i3, i4 = i1 + i3, i2 + i4
    bbox = category_id + ' ' + str(i1) + ' ' + str(i2) + ' ' + str(i3) + ' ' + str(i4) + '\n'

    imp = os.path.join('./data/val2017/', label_p)
    with open(imp, 'a') as f:
        f.write(bbox)

100%|███████████████████████████████████████████████████████████████████████████| 36781/36781 [05:11<00:00, 118.24it/s]


In [74]:
import yaml
with open('./data/coco.yaml') as f:
    data_dict = yaml.load(f, Loader=yaml.FullLoader)
data_dict['names']

# function 測試

In [24]:
import importlib
import utils.datasets
importlib.reload(utils.datasets)

path = './data/val2017-image.txt'
val_dataset = utils.datasets.LoadImagesAndLabels(path)

Scanning labels data\val2017.cache (5612 found, 0 missing, 1 empty, 0 duplicate, for 5613 images): 100%|█| 5613/5613 [0


In [25]:
x = val_dataset[0]

[[          1      171.44      -21.11      390.14      325.57]
 [         35        0.48      450.61       410.2      488.81]]
[[          1      280.79      152.23       218.7      346.68]
 [         35      205.34      469.71      409.72        38.2]]
[[          1     0.43873     0.23786     0.34172     0.54169]
 [         35     0.32084     0.73392     0.64019    0.059688]]


In [15]:
x[1]

tensor([[  0.00000,   1.00000, 280.79001,  29.87148, 218.70000, 230.21719],
        [  0.00000,  35.00000, 205.34000, 240.69804, 409.72003,  25.36719]])

In [2]:
val_dataset.labels[0]

array([[          1,      280.79,       44.73,       218.7,      346.68],
       [         35,      205.34,      362.21,      409.72,        38.2]], dtype=float32)

In [4]:
val_dataset.img_files

['data\\val2017\\000000000785.jpg',
 'data\\val2017\\000000000872.jpg',
 'data\\val2017\\000000000872.jpg',
 'data\\val2017\\000000000885.jpg',
 'data\\val2017\\000000000885.jpg',
 'data\\val2017\\000000000885.jpg',
 'data\\val2017\\000000000885.jpg',
 'data\\val2017\\000000000885.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001000.jpg',
 'data\\val2017\\000000001268.jpg',
 'data\\val2017\\000000001296.jpg',
 'data\\val2017\\000000001353.jpg',
 'data\\val2017\\000000001353.jpg',
 'data\\val2017\\000000001353.jpg',
 'data\\val2017\\000000001353.jpg',
 'data\\val2017\\000000001584.jpg',
 'data\\val2017\\00000000158

In [5]:
val_dataset.label_files

['data\\val2017\\000000000785.txt',
 'data\\val2017\\000000000872.txt',
 'data\\val2017\\000000000872.txt',
 'data\\val2017\\000000000885.txt',
 'data\\val2017\\000000000885.txt',
 'data\\val2017\\000000000885.txt',
 'data\\val2017\\000000000885.txt',
 'data\\val2017\\000000000885.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001000.txt',
 'data\\val2017\\000000001268.txt',
 'data\\val2017\\000000001296.txt',
 'data\\val2017\\000000001353.txt',
 'data\\val2017\\000000001353.txt',
 'data\\val2017\\000000001353.txt',
 'data\\val2017\\000000001353.txt',
 'data\\val2017\\000000001584.txt',
 'data\\val2017\\00000000158

# train

In [9]:
import cv2
img = cv2.imread('data\\val2017\\000000000785.jpg')
img.shape

(425, 640, 3)

In [2]:
from torch.utils.tensorboard import SummaryWriter

D:\python\dataScienceV2\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ModuleNotFoundError: No module named 'tensorboard'

In [7]:
import torch.nn as nn
nn.Mish

torch.nn.modules.activation.Mish

In [11]:
!pip install scipy

     -------------------------------------- 42.5/42.5 MB 604.4 kB/s eta 0:00:00



[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
!python train.py --batch-size 2 --img 224 224 --data data/coco.yaml --cfg models/yolov4-p5.yaml --device 0 --name yolov4-p5-tune --hyp data/hyp.finetune.yaml --epochs 450 --resume

D:\study\justLearn\forwork\papers\yolo\yolov4-csp\yolov4_csp True data/coco.yaml
D:\study\justLearn\forwork\papers\yolo\yolov4-csp\yolov4_csp True models/yolov4-p5.yaml
D:\study\justLearn\forwork\papers\yolo\yolov4-csp\yolov4_csp True data/hyp.finetune.yaml
Using CUDA device0 _CudaDeviceProperties(name='NVIDIA GeForce GTX 1650 Ti', total_memory=4095MB)

Namespace(weights='yolov4-p5.pt', cfg='models/yolov4-p5.yaml', data='data/coco.yaml', hyp='data/hyp.finetune.yaml', epochs=450, batch_size=2, img_size=[224, 224], rect=False, resume='get_last', nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=False, name='yolov4-p5-tune', device='0', multi_scale=False, single_cls=False, adam=False, sync_bn=False, local_rank=-1, logdir='runs/', total_batch_size=2, world_size=1, global_rank=-1)
Start Tensorboard with "tensorboard --logdir runs/", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls':

Traceback (most recent call last):
  File "D:\study\justLearn\forwork\papers\yolo\yolov4-csp\yolov4_csp\train.py", line 445, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:\study\justLearn\forwork\papers\yolo\yolov4-csp\yolov4_csp\train.py", line 63, in train
    attempt_download(weights)  # download if not found locally
  File "D:\study\justLearn\forwork\papers\yolo\yolov4-csp\yolov4_csp\utils\google_utils.py", line 33, in attempt_download
    raise Exception(msg)
Exception: yolov4-p5.pt missing


In [19]:
import os
os.getcwd()

'D:\\study\\justLearn\\forwork\\papers\\yolo\\yolov4-csp\\yolov4_csp'

In [6]:
!pip show torch

Name: torch
Version: 1.13.1+cu116
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: d:\python\datasciencev2\lib\site-packages
Requires: typing-extensions
Required-by: torchaudio, torchvision
